// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaurirxmWStpQp9EeLsSfNMYDgsLmNYJY',
    appId: '1:768054562277:web:401f31734cc9748bb8b30c',
    messagingSenderId: '768054562277',
    projectId: 'consumewise-f494e',
    authDomain: 'consumewise-f494e.firebaseapp.com',
    storageBucket: 'consumewise-f494e.appspot.com',
    measurementId: 'G-KNP78BGBPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB22uPbNKE1BFbgabkYARkxgZh9ySah8s',
    appId: '1:768054562277:android:3976e14dc627f0b8b8b30c',
    messagingSenderId: '768054562277',
    projectId: 'consumewise-f494e',
    storageBucket: 'consumewise-f494e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHla3-TdikqUKARFlYl_EP7AJVwPHiTso',
    appId: '1:768054562277:ios:56469cac39cd1d86b8b30c',
    messagingSenderId: '768054562277',
    projectId: 'consumewise-f494e',
    storageBucket: 'consumewise-f494e.appspot.com',
    iosBundleId: 'com.example.genAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHla3-TdikqUKARFlYl_EP7AJVwPHiTso',
    appId: '1:768054562277:ios:56469cac39cd1d86b8b30c',
    messagingSenderId: '768054562277',
    projectId: 'consumewise-f494e',
    storageBucket: 'consumewise-f494e.appspot.com',
    iosBundleId: 'com.example.genAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaurirxmWStpQp9EeLsSfNMYDgsLmNYJY',
    appId: '1:768054562277:web:40c91de4f9790984b8b30c',
    messagingSenderId: '768054562277',
    projectId: 'consumewise-f494e',
    authDomain: 'consumewise-f494e.firebaseapp.com',
    storageBucket: 'consumewise-f494e.appspot.com',
    measurementId: 'G-X2RFM1P06Y',
  );
}
